import localFont from "next/font/local";
import Head from "next/head";
import "./globals.css";
import Provider from "./provider";
import ThemeSwitcher from "./ThemeSwitcher";
import LoaderProvider from "./LoaderProvider";

const myFont = localFont({
  src: "../../public/DMSans-VariableFont_opsz,wght.ttf",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={myFont.className}>
        <Provider>
          <ThemeSwitcher />
          {/* <LoaderProvider> */}
            <div id="main-content">{children}</div>
          {/* </LoaderProvider> */}
        </Provider>
      </body>
    </html>
  );
}
